ekf_local:
  ros__parameters:
    frequency: 50.0
    two_d_mode: false
    publish_tf: true
    publish_acceleration: false
    print_diagnostics: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Use IMU data
    imu0: /livox/imu
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    # Use corrected Odometry from loam_interface for relative Twist
    odom0: /lidar_odometry
    odom0_config: [true,  true,  true,
                   true,  true,  true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: true
    odom0_relative: false
    odom0_queue_size: 10

ekf_global:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false
    publish_tf: true
    publish_acceleration: false
    print_diagnostics: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # Use IMU data
    imu0: /livox/imu
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    # Use corrected Odometry from loam_interface for relative Twist
    odom0: /lidar_odometry
    odom0_config: [true,  true,  true,
                   true,  true,  true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: true
    odom0_relative: false
    odom0_queue_size: 10

    # Use Small GICP absolute Pose
    pose0: /gicp_pose
    pose0_config: [true,  true,  true,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    pose0_differential: false
    pose0_relative: false
    pose0_queue_size: 10
    # pose0_rejection_threshold: 5.0  # 注释掉，允许 GICP 发生大于 5.0 sigma 的跳变（如重定位）
